version: '2'
services:
  elasticsearch:
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
  logstash:
    links:
      - elasticsearch
      - redis
    volumes:
      - ./logstash/indexer/config:/etc/logstash/conf.d
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
