version: '3'
services:
  elasticsearch:
    ports:
    - "${ELASTICSEARCH_HTTP_PORT}:9200"
    - "${ELASTICSEARCH_TCP_PORT}:9300"
    networks:
    - ${ELK_NETWORKS}
  logstash:
    command: ["-e", "$LOGSTASH_INDEXER_CONFIG_STRING"]
    networks:
    - ${ELK_NETWORKS}
  kibana:
    image: "${KIBANA_IMAGE}"
    ports:
    - "${KIBANA_PORT}:5601"
    networks:
    - ${ELK_NETWORKS}
    command: ["kibana", "-e", "http://${KIBANA_ELASTICSEARCH_ADDRESS}"]
  redis:
    image: "${REDIS_IMAGE}"
    volumes:
    - redis-data:/data
    networks:
    - ${ELK_NETWORKS}

volumes:
  elasticsearch-data:
    driver: nfs
    driver_opts:
      share: ${ELASTICSEARCH_DATA_PATH}
  redis-data:
    driver: nfs
    driver_opts:
      share: ${REDIS_DATA_PATH}

networks:
  ${ELK_NETWORKS}:
    driver: overlay
