version: '3'
services:
  elasticsearch:
    image: "${ELASTICSEARCH_IMAGE}"
    env_file:
    - ./env_files/${PLATFORM}/elasticsearch.env
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
  logstash:
    image: "${LOGSTASH_IMAGE}"
